stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/mushrooms.csv
    outs:
    - data/raw/mushrooms.csv

  preprocessing:
    cmd: python src/preprocessing.py --config=params.yaml
    deps:
    - src/preprocessing.py
    - data/raw/mushrooms.csv
    outs: 
    - data/processed/processed_final.csv
    - saved_models/ord_enc.joblib

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/processed/processed_final.csv
    outs:
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.Adaboost.params.n_estimators
    - estimators.Adaboost.params.learning_rate
    - estimators.Adaboost.params.algorithm
    
    # outs:
    # - saved_models/model.joblib

#    metrics:
#    - report/scores.json:
#        cache: false
#    - report/params.json:
#        cache: false

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py
